DROP DATABASE IF EXISTS Mystic_Tuner_Application;
CREATE DATABASE Mystic_Tuner_Application;

DROP TABLE IF EXISTS Deck;
CREATE TABLE Deck (
	DID INT PRIMARY KEY,
	userId INT NOT NULL,
	deckType VARCHAR(100) NOT NULL, 
	deckName VARCHAR(100) NOT NULL
);

DROP TABLE IF EXISTS Card;
CREATE TABLE Card (
	deckId INT NOT NULL,
	name VARCHAR(200) NOT NULL,
	sideBoard BOOLEAN,
	cardType VARCHAR(20),
	FOREIGN KEY (deckId) REFERENCES Deck(DID) ON DELETE CASCADE
);

DROP TABLE IF EXISTS CardNames;
CREATE TABLE CardNames (
	name VARCHAR(200) PRIMARY KEY
);